[versions]
agp = "9.0.0"
kotlin = "2.3.10"

coreKtx = "1.17.0"
activityCompose = "1.12.4"

composeBom = "1.10.3"
material3 = "1.4.0"

backdrop = "2.0.0-alpha03"
shapes = "1.2.0"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }

androidx-compose-foundation = { group = "androidx.compose.foundation", name = "foundation", version.ref = "composeBom" }
androidx-compose-ui = { group = "androidx.compose.ui", name = "ui", version.ref = "composeBom" }
androidx-compose-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics", version.ref = "composeBom" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3", version.ref = "material3" }

kyant0-backdrop = { group = "io.github.kyant0", name = "backdrop", version.ref = "backdrop" }
kyant0-shapes = { group = "io.github.kyant0", name = "shapes", version.ref = "shapes" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
